import { createAdminClient } from '@/utils/supabase/admin';
import { NormalizationLog } from './inputNormalizers';

/**
 * Asynchronously persists normalization logs to the database without blocking the main execution flow.
 * Uses the admin client to bypass RLS if necessary, ensuring logs are always captured.
 *
 * @param logs Array of normalization events generated by inputNormalizers
 * @param entityType The type of entity being normalized (e.g., 'minifigures')
 * @param source The origin of the request (e.g., 'admin_panel', 'cto_api', 'import_script')
 * @param entityId (Optional) The ID of the entity if it's an update, or null if it's a new insert
 * @param userId (Optional) The ID of the user who triggered the normalization
 */
export async function persistNormalizationLogs(
  logs: NormalizationLog[],
  entityType: string,
  source: string,
  entityId?: string | null,
  userId?: string | null
): Promise<void> {
  if (!logs || logs.length === 0) return;

  try {
    const adminClient = createAdminClient();

    const payload = logs.map(log => ({
      entity_type: entityType,
      entity_id: entityId || null,
      field_name: log.field,
      original_value: log.originalValue !== undefined && log.originalValue !== null ? String(log.originalValue) : null,
      normalized_value: log.normalizedValue !== undefined && log.normalizedValue !== null ? String(log.normalizedValue) : null,
      source: source,
      user_id: userId || null,
      created_at: log.timestamp || new Date().toISOString()
    }));

    // Fire-and-forget DB insertion
    const { error } = await adminClient.from('data_normalization_logs').insert(payload);
    
    if (error) {
      // We don't throw the error back to the caller to maintain failure-safety
      console.error('[DataGovernance] Failed to persist normalization logs:', error.message);
    } else {
        console.log(`[DataGovernance] Successfully persisted ${logs.length} normalization logs to DB.`);
    }
  } catch (err: any) {
    // Ultimate fallback catch to guarantee main thread isolation
    console.error('[DataGovernance] Fatal error persisting logs:', err.message);
  }
}
